// This file is generated by rust-protobuf 2.14.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `src/tensorboardrs/proto/plugin_text.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_14_0;

#[derive(PartialEq,Clone,Default)]
pub struct TextPluginData {
    // message fields
    pub version: i32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a TextPluginData {
    fn default() -> &'a TextPluginData {
        <TextPluginData as ::protobuf::Message>::default_instance()
    }
}

impl TextPluginData {
    pub fn new() -> TextPluginData {
        ::std::default::Default::default()
    }

    // int32 version = 1;


    pub fn get_version(&self) -> i32 {
        self.version
    }
    pub fn clear_version(&mut self) {
        self.version = 0;
    }

    // Param is passed by value, moved
    pub fn set_version(&mut self, v: i32) {
        self.version = v;
    }
}

impl ::protobuf::Message for TextPluginData {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.version = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.version != 0 {
            my_size += ::protobuf::rt::value_size(1, self.version, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.version != 0 {
            os.write_int32(1, self.version)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TextPluginData {
        TextPluginData::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                    "version",
                    |m: &TextPluginData| { &m.version },
                    |m: &mut TextPluginData| { &mut m.version },
                ));
                ::protobuf::reflect::MessageDescriptor::new_pb_name::<TextPluginData>(
                    "TextPluginData",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static TextPluginData {
        static mut instance: ::protobuf::lazy::Lazy<TextPluginData> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            instance.get(TextPluginData::new)
        }
    }
}

impl ::protobuf::Clear for TextPluginData {
    fn clear(&mut self) {
        self.version = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TextPluginData {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TextPluginData {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n)src/tensorboardrs/proto/plugin_text.proto\x12\rtensorboardrs\"*\n\x0e\
    TextPluginData\x12\x18\n\x07version\x18\x01\x20\x01(\x05R\x07versionJ\
    \x8e\x08\n\x06\x12\x04\x0f\0\x1a\x01\n\x9f\x05\n\x01\x0c\x12\x03\x0f\0\
    \x122\x94\x05\x20Copyright\x202017\x20The\x20TensorFlow\x20Authors.\x20A\
    ll\x20Rights\x20Reserved.\n\nLicensed\x20under\x20the\x20Apache\x20Licen\
    se,\x20Version\x202.0\x20(the\x20\"License\");\nyou\x20may\x20not\x20use\
    \x20this\x20file\x20except\x20in\x20compliance\x20with\x20the\x20License\
    .\nYou\x20may\x20obtain\x20a\x20copy\x20of\x20the\x20License\x20at\n\nht\
    tp://www.apache.org/licenses/LICENSE-2.0\n\nUnless\x20required\x20by\x20\
    applicable\x20law\x20or\x20agreed\x20to\x20in\x20writing,\x20software\nd\
    istributed\x20under\x20the\x20License\x20is\x20distributed\x20on\x20an\
    \x20\"AS\x20IS\"\x20BASIS,\nWITHOUT\x20WARRANTIES\x20OR\x20CONDITIONS\
    \x20OF\x20ANY\x20KIND,\x20either\x20express\x20or\x20implied.\nSee\x20th\
    e\x20License\x20for\x20the\x20specific\x20language\x20governing\x20permi\
    ssions\x20and\nlimitations\x20under\x20the\x20License.\n================\
    ==============================================================\n\x08\n\
    \x01\x02\x12\x03\x11\0\x16\n\xe6\x01\n\x02\x04\0\x12\x04\x17\0\x1a\x01\
    \x1a\xd9\x01\x20Text\x20summaries\x20created\x20by\x20the\x20`tensorboar\
    d.plugins.text.summary`\n\x20module\x20will\x20include\x20`SummaryMetada\
    ta`\x20whose\x20`plugin_data`\x20field\x20has\n\x20as\x20`content`\x20a\
    \x20binary\x20string\x20that\x20is\x20the\x20encoding\x20of\x20an\n\x20`\
    TextPluginData`\x20proto.\n\n\n\n\x03\x04\0\x01\x12\x03\x17\x08\x16\n9\n\
    \x04\x04\0\x02\0\x12\x03\x19\x02\x14\x1a,\x20Version\x20`0`\x20is\x20the\
    \x20only\x20supported\x20version.\n\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\
    \x19\x02\x07\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x19\x08\x0f\n\x0c\n\x05\
    \x04\0\x02\0\x03\x12\x03\x19\x12\x13b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
